pool:
  vmImage: ubuntu-latest

jobs:
- job: run_banking_application
  displayName: Run Banking Application
  steps:

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.10'
      displayName: "Set up Python 3.10"

    - script: |
        python app.py
      displayName: "Run Banking Application Script"